### ISSUE TITLE
Issues setting LFG Channel settings

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/genesis#454]
**Summary:**

---
**If issue, Reproduction:**

---
**Mockups, screenshots, evidence:**
```bash
TypeError: Cannot read property '1' of null
     at SetLFGChannel.run (/genesis/src/commands/LFG/SetLFGChannel.js:28:26)
     at /genesis/src/eventHandlers/CommandHandler.js:150:38
```

**Comment by TobiTenno** [comment]
fixed in slash commands (#466)
